config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  
  get '/:handle', to: 'users#show', as: :profile
  get '/:current_user_handle', to: 'users#show', as: :current_user_profile
  resources :categories
  get '/categories/new', to: 'categories#new', as: :add_category
  resources :stories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :stories, dependent: :delete_all
  has_one_attached :image
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :categories

  def full_name
    [first_name, last_name].join(' ')
  end

  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def delete
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(name: params[:category][:name], image: params[:category][:image])
    redirect_to current_user_profile_path
  end

  def destroy
    category = Category.destroy(params[:id])
    head :no_content
  end

  def show
    @categories = Category.all.select { |category| category.user_id == current_user.id }
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to current_user_profile_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :image)
  end

  def current_user_profile_path
    "/#{current_user.username} #{current_user.id}"
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = User.find_by(username: current_user.username)
    @current_user_handle = @user.username + "#{@user.id}"
    print(@current_user_handle)
  end

  def user_home
    @page = Page.new(params[:user_id])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def new
    @story = Story.new
    @months = create_array_of_numbers(1, 12, true)
    @years = create_array_of_numbers(1900, Time.new.year, false)
  end

  def create
    @story = Story.new(story_params_with_timestamp)
    if @story.save
      redirect_to current_user_profile_path
    else
      render :new
    end
  end

  private

  def timestamp
    month = params[:month]
    year = params[:year]
    return Time.new(year.to_i, month.to_i, 10)
  end

  def story_params
    params.require(:story).permit(:title, :body, :month, :year, :category_id)
  end

  def story_params_with_timestamp
    { "title" => params[:title],
      "body" => params[:body],
      "timestamp" => timestamp,
      "category_id" => params[:category_id]
    }
  end

  def create_array_of_numbers(from, to, ascending)
    n = from;
    array = []
    while n <= to do
      array.push(n)
      n += 1
    end
    if ascending
      return array
    else
      return array.reverse
    end
  end

  def current_user_profile_path
    "/#{current_user.username} #{current_user.id}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username: current_user.username)
    @categories = @user.categories
    @handle = handle(@user)
    @stories = stories
  end

  def handle(user)
    user.username + "#{user.id}"
  end

  def stories
    allStories = []
    @categories.each do |category|
      category.stories.each do |story|
        allStories.push(story)
      end
    end
    return allStories
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_categories.html.erb
<div class="cards">
  <% categories.each do |category| %>
    <div class="categoryCard">
      <% if category.image.attached? %>
        <%= image_tag category.image, class: "categoryImage" %>
      <% end %>
      <p class="categoryName">
        <%= category.name %>
      </p>
      <div class="categoryLinks">
        <%= link_to "DELETE", category_path(category), method: :delete, data: { confirm: "Delete category and all associated stories?" }, class: "deleteCategoryLink" %>
        <%= link_to "EDIT", edit_category_path(category), class: "editCategoryLink" %>
      </div>
      
    </div>
  <% end %>

</div>

app/views/categories/_form.html.erb
<div id="newCategoryForm">
  <%= form_for @category, html: { multipart: true } do |f| %>
    <%= f.label :name, class: "label" %>
    <%= f.text_field :name, id: "name", class: "field" %>
    <br/>
    <% f.label :image, class: "label" %>
    <%= f.drag_and_drop_file_field :image, "Drag and drop image here" %>

    <p id="createCategoryButton">
      <%= f.submit %>
    </p>

  <% end %>
</div>

<script>
  (function() {
    var reader = new FileReader()
    var form = document.querySelector('#new_category')
    var field = document.querySelector('#category_image')
    var preview = document.querySelector('#asdndz-category_image')

    reader.onload = function(e) {
      preview.style.backgroundImage = `url(${e.srcElement.result})`
    }

    field.addEventListener('dnd-upload:initialize', function(e) {
      reader.readAsDataURL(e.detail.file)
    }, false)

    form.addEventListener('click', function(e) {
      if (event.target.dataset.dndDelete === 'true') {
        preview.style.backgroundImage = ''
      }
    }, true)
  })()
</script>

app/views/categories/edit.html.erb
<div>
  <%= render 'categories/form', categories: @categories %>
</div>

app/views/categories/new.html.erb
<div>
  <%= render 'categories/form', categories: @categories %>
</div>

app/views/categories/show.html.erb
<div id="categoriesAndStories">
  <div id="categoryButtons">
    <%= collection_select :category_id, @categories,:id,:name, include_blank: true %>
  </div>
  <div id="categoriesList">
    <%= render 'categories/categories', categories: @categories %>
    <%= @what %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuasiNormalActivity2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar navbar-expand-lg bg-dark navbar-dark mb-3" id="navigationBar">
      <div class="main">
        <%= link_to image_tag("quasi_normal_activity_logo_2.png"), root_path, class: 'navbar-brand' %>

        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: 'nav-link' %>
          </li>
        </ul>

        <ul class="navbar-nav">
          <li class="nav-item">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to current_user.full_name, root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Log Out", destroy_user_session_path, class: 'nav-link', method: :delete %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Create an Account", new_user_registration_path, class: 'btn btn-primary' %>
              </li>
            <% end %>
          </li>
        </ul>

      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h2>Quasi Normal Activity main page</h2>

<% if signed_in? %>
  <%= link_to "Your page", "/#{@current_user_handle}" %>
<% end %>

<%= :current_user_profile %>

app/views/stories/_stories.html.erb
<div class="storiesContainer">
  <% stories.each do |story| %>  
    <div class="storyCard">
      <div class="storyHeader">
        <div class="storyHeaderTitle">
          <h4><%= story.title.upcase %></h4>
        </div>
        <div class="storyHeaderImage">
          <%= image_tag story.category.image, class: "storyHeaderRound" %>
        </div>
      </div>
      <p>
        <%= story.category.name %>
      </p>
      <p class="timestamp">
        <%= image_tag image_path("calendar.png"), class: "icon" %>
        <%= story.timestamp.strftime("%B %Y") %>
      </p>
      <br/>
      <br/>
      <p>
        <%= story.body %>
      </p>
    </div>
  <% end %>
</div>

app/views/stories/new.html.erb
<div id="newStoryForm">
  <%= form_with url: stories_path, html: { multipart: true } do |f| %>
    <%= f.label :title, class: "titleLabel" %>
    <%= f.text_field :title, id: "name", class: "titleField" %>
    <br/>
    <%= f.label :body, class: "bodyLabel" %>
    <%= f.text_area :body, id: "body", class: "bodyField", rows: "8", cols: "45" %>
    <br/>
    <div class="timeSelection">
      <%= f.label :month, class: "labelMonth" %>
      <%= f.select(:month, @months, class: "curtain")%>
      <%= f.label :year, class: "labelYear" %>
      <%= f.select(:year, @years, class: "curtain")%>
    </div>
    <br/>
    <div class="categorySelection">
      <%= f.label :category, class: "labelCategory" %>
      <%= f.collection_select :category_id, Category.order(:name),:id,:name, :prompt => " -- Select -- ", include_blank: false %>
    </div>

    <div class="createStoryButton">
      <%= f.submit "Save", id: "saveButton" %>
    </p>

  <% end %>
</div>

app/views/users/show.html.erb
<h2 class="usernameProfile"><%= @user.username %></h2>

<div id="showContainer">
  <% if (current_user.id == @user.id) %>
    <div id="sidebar">
      <%= link_to "New story", :new_story, class: "newStory" %>
      <%= link_to "Add category", :add_category, class: "addCategory" %>
    </div>
  <% end %>

  <div id="categoriesAndStories">
    <div id="categoriesList">
      <%= render 'categories/categories', categories: @categories %>
    </div>
    <div id="storiesList">
      <%= render 'stories/stories', stories: @stories %>
    </div>
  </div>
  
</div>